// Generated by scripts/embed-migrations.ts from drizzle/. Do not edit; run `pnpm db:generate`.
import type { MigrationMeta } from "drizzle-orm/migrator";

export const migrations: MigrationMeta[] = [
  {
    "sql": [
      "CREATE TABLE `albums` (\n\t`id` text PRIMARY KEY,\n\t`name` text NOT NULL,\n\t`artist` text,\n\t`artistId` text,\n\t`coverArt` text,\n\t`created` text NOT NULL,\n\t`duration` real NOT NULL,\n\t`genre` text,\n\t`playCount` real,\n\t`songCount` integer NOT NULL,\n\t`starred` text,\n\t`year` integer,\n\t`version` text,\n\t`played` text,\n\t`userRating` real,\n\t`recordLabels` text,\n\t`musicBrainzId` text,\n\t`genres` text,\n\t`artists` text,\n\t`displayArtist` text,\n\t`releaseTypes` text,\n\t`moods` text,\n\t`sortName` text,\n\t`originalReleaseDate` text,\n\t`releaseDate` text,\n\t`isCompilation` integer,\n\t`explicitStatus` text,\n\t`discTitles` text,\n\t`coverArtPath` text,\n\t`coverArtSourceId` text\n);\n",
      "\nCREATE TABLE `artists` (\n\t`id` text PRIMARY KEY,\n\t`name` text NOT NULL,\n\t`starred` text,\n\t`userRating` real,\n\t`averageRating` real,\n\t`coverArt` text,\n\t`artistImageUrl` text,\n\t`coverArtPath` text,\n\t`coverArtSourceId` text\n);\n",
      "\nCREATE TABLE `covers` (\n\t`key` text PRIMARY KEY,\n\t`fileName` text NOT NULL\n);\n",
      "\nCREATE TABLE `credentials` (\n\t`id` integer PRIMARY KEY,\n\t`url` text NOT NULL,\n\t`username` text NOT NULL,\n\t`password` text NOT NULL,\n\t`encrypted` integer NOT NULL\n);\n",
      "\nCREATE TABLE `player_queue` (\n\t`id` integer PRIMARY KEY,\n\t`snapshot` text NOT NULL\n);\n",
      "\nCREATE TABLE `playlists` (\n\t`id` text PRIMARY KEY,\n\t`serverId` text,\n\t`base` text,\n\t`local` text,\n\t`revision` integer NOT NULL\n);\n",
      "\nCREATE TABLE `songs` (\n\t`id` text PRIMARY KEY,\n\t`title` text NOT NULL,\n\t`isDir` integer NOT NULL,\n\t`album` text,\n\t`albumId` text,\n\t`artist` text,\n\t`artistId` text,\n\t`averageRating` real,\n\t`bitRate` real,\n\t`bookmarkPosition` real,\n\t`contentType` text,\n\t`coverArt` text,\n\t`created` text,\n\t`discNumber` integer,\n\t`duration` real,\n\t`genre` text,\n\t`isVideo` integer,\n\t`originalHeight` integer,\n\t`originalWidth` integer,\n\t`parent` text,\n\t`path` text,\n\t`playCount` real,\n\t`size` real,\n\t`starred` text,\n\t`suffix` text,\n\t`track` integer,\n\t`transcodedContentType` text,\n\t`transcodedSuffix` text,\n\t`type` text,\n\t`userRating` real,\n\t`year` integer,\n\t`played` text,\n\t`bpm` real,\n\t`comment` text,\n\t`sortName` text,\n\t`musicBrainzId` text,\n\t`genres` text,\n\t`artists` text,\n\t`displayArtist` text,\n\t`albumArtists` text,\n\t`displayAlbumArtist` text,\n\t`contributors` text,\n\t`displayComposer` text,\n\t`moods` text,\n\t`replayGain` text,\n\t`explicitStatus` text\n);\n",
      "\nCREATE TABLE `sync_state` (\n\t`id` integer PRIMARY KEY,\n\t`indexesLastModified` integer,\n\t`lastFullSyncAt` text,\n\t`lastQuickSyncAt` text\n);\n",
      "\nCREATE INDEX `albums_artist_id` ON `albums` (`artistId`);",
      "\nCREATE INDEX `playlists_server_id` ON `playlists` (`serverId`);",
      "\nCREATE INDEX `songs_album_id` ON `songs` (`albumId`);"
    ],
    "bps": true,
    "folderMillis": 1790932470000,
    "hash": "c4a9361f1b3b0a868ea30275c257f6686bd8ca8be09215026976e38a8d89b944",
    "name": "20261002091430_init"
  },
  {
    "sql": [
      "CREATE TABLE `queue_items` (\n\t`key` text PRIMARY KEY,\n\t`list` text NOT NULL,\n\t`position` integer NOT NULL,\n\t`track` text NOT NULL\n);\n",
      "\nCREATE TABLE `queue_state` (\n\t`id` integer PRIMARY KEY,\n\t`nowPlayingKey` text,\n\t`nowPlayingOrigin` text,\n\t`source` text,\n\t`resumePositionSeconds` real NOT NULL\n);\n",
      "\nDROP TABLE `player_queue`;"
    ],
    "bps": true,
    "folderMillis": 1790948438000,
    "hash": "a5bafe9fac853212a246a21f97c93f0db6e5d655194d5e90c465bddb9ab64dc0",
    "name": "20261002134038_queue_tables"
  },
  {
    "sql": [
      "ALTER TABLE `songs` ADD `titleSortKey` text DEFAULT '' NOT NULL;",
      "\nCREATE INDEX `songs_title_sort` ON `songs` (`titleSortKey`,`id`);"
    ],
    "bps": true,
    "folderMillis": 1791231005000,
    "hash": "c5fc5232691042e9551871e71949b5ab22ad21568adc1bd88860d24b557f1f39",
    "name": "20261005201005_song_title_sort_key"
  }
];
