/**
 * Embeds the drizzle-kit migrations in `drizzle/` into `src/db/migrations.generated.ts`, so the
 * main-process bundle carries them and no migration folder has to ship with the app.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { readMigrationFiles } from "drizzle-orm/migrator";

const migrationsFolder = fileURLToPath(new URL("../drizzle", import.meta.url));
const target = fileURLToPath(new URL("../src/db/migrations.generated.ts", import.meta.url));

export const renderMigrations = () => {
  const migrations = readMigrationFiles({ migrationsFolder });
  return `// Generated by scripts/embed-migrations.ts from drizzle/. Do not edit; run \`pnpm db:generate\`.
import type { MigrationMeta } from "drizzle-orm/migrator";

export const migrations: MigrationMeta[] = ${JSON.stringify(migrations, null, 2)};
`;
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(target, renderMigrations());
  console.log(`Embedded migrations into ${target}`);
}
