/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSongsRouteImport } from './routes/app/songs'
import { Route as AppAlbumsRouteImport } from './routes/app/albums'
import { Route as AppSongsIndexRouteImport } from './routes/app/songs.index'
import { Route as AppAlbumsIndexRouteImport } from './routes/app/albums.index'
import { Route as AppAlbumsAlbumIdRouteImport } from './routes/app/albums.$albumId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSongsRoute = AppSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbumsRoute = AppAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppRoute,
} as any)
const AppSongsIndexRoute = AppSongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSongsRoute,
} as any)
const AppAlbumsIndexRoute = AppAlbumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlbumsRoute,
} as any)
const AppAlbumsAlbumIdRoute = AppAlbumsAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AppAlbumsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/albums': typeof AppAlbumsRouteWithChildren
  '/app/songs': typeof AppSongsRouteWithChildren
  '/app/albums/$albumId': typeof AppAlbumsAlbumIdRoute
  '/app/albums/': typeof AppAlbumsIndexRoute
  '/app/songs/': typeof AppSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/albums/$albumId': typeof AppAlbumsAlbumIdRoute
  '/app/albums': typeof AppAlbumsIndexRoute
  '/app/songs': typeof AppSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/albums': typeof AppAlbumsRouteWithChildren
  '/app/songs': typeof AppSongsRouteWithChildren
  '/app/albums/$albumId': typeof AppAlbumsAlbumIdRoute
  '/app/albums/': typeof AppAlbumsIndexRoute
  '/app/songs/': typeof AppSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/albums'
    | '/app/songs'
    | '/app/albums/$albumId'
    | '/app/albums/'
    | '/app/songs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/albums/$albumId' | '/app/albums' | '/app/songs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/albums'
    | '/app/songs'
    | '/app/albums/$albumId'
    | '/app/albums/'
    | '/app/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/songs': {
      id: '/app/songs'
      path: '/songs'
      fullPath: '/app/songs'
      preLoaderRoute: typeof AppSongsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/albums': {
      id: '/app/albums'
      path: '/albums'
      fullPath: '/app/albums'
      preLoaderRoute: typeof AppAlbumsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/songs/': {
      id: '/app/songs/'
      path: '/'
      fullPath: '/app/songs/'
      preLoaderRoute: typeof AppSongsIndexRouteImport
      parentRoute: typeof AppSongsRoute
    }
    '/app/albums/': {
      id: '/app/albums/'
      path: '/'
      fullPath: '/app/albums/'
      preLoaderRoute: typeof AppAlbumsIndexRouteImport
      parentRoute: typeof AppAlbumsRoute
    }
    '/app/albums/$albumId': {
      id: '/app/albums/$albumId'
      path: '/$albumId'
      fullPath: '/app/albums/$albumId'
      preLoaderRoute: typeof AppAlbumsAlbumIdRouteImport
      parentRoute: typeof AppAlbumsRoute
    }
  }
}

interface AppAlbumsRouteChildren {
  AppAlbumsAlbumIdRoute: typeof AppAlbumsAlbumIdRoute
  AppAlbumsIndexRoute: typeof AppAlbumsIndexRoute
}

const AppAlbumsRouteChildren: AppAlbumsRouteChildren = {
  AppAlbumsAlbumIdRoute: AppAlbumsAlbumIdRoute,
  AppAlbumsIndexRoute: AppAlbumsIndexRoute,
}

const AppAlbumsRouteWithChildren = AppAlbumsRoute._addFileChildren(
  AppAlbumsRouteChildren,
)

interface AppSongsRouteChildren {
  AppSongsIndexRoute: typeof AppSongsIndexRoute
}

const AppSongsRouteChildren: AppSongsRouteChildren = {
  AppSongsIndexRoute: AppSongsIndexRoute,
}

const AppSongsRouteWithChildren = AppSongsRoute._addFileChildren(
  AppSongsRouteChildren,
)

interface AppRouteChildren {
  AppAlbumsRoute: typeof AppAlbumsRouteWithChildren
  AppSongsRoute: typeof AppSongsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAlbumsRoute: AppAlbumsRouteWithChildren,
  AppSongsRoute: AppSongsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
