import { type AlbumWithSongsID3, type Child } from "subsonic-api";

import { albumsTable, songsTable } from "../drizzle/schema.js";

export function toSongRow(album: AlbumWithSongsID3, song: Child): typeof songsTable.$inferInsert {
  return {
    id: song.id,
    album: song.album ?? album.name,
    albumId: song.albumId ?? album.id,
    artist: song.artist ?? null,
    artistId: song.artistId ?? null,
    averageRating: song.averageRating ?? null,
    bitRate: song.bitRate ?? null,
    bookmarkPosition: song.bookmarkPosition ?? null,
    contentType: song.contentType ?? null,
    coverArt: song.coverArt ?? null,
    created: song.created ?? null,
    discNumber: song.discNumber ?? null,
    duration: song.duration ?? null,
    genre: song.genre ?? null,
    isDir: song.isDir,
    isVideo: song.isVideo ?? null,
    originalHeight: song.originalHeight ?? null,
    originalWidth: song.originalWidth ?? null,
    parent: song.parent ?? null,
    path: song.path ?? null,
    playCount: song.playCount ?? null,
    size: song.size ?? null,
    starred: song.starred ?? null,
    suffix: song.suffix ?? null,
    title: song.title,
    track: song.track ?? null,
    transcodedContentType: song.transcodedContentType ?? null,
    transcodedSuffix: song.transcodedSuffix ?? null,
    type: song.type ?? null,
    userRating: song.userRating ?? null,
    year: song.year ?? null,
    played: song.played ?? null,
    bpm: song.bpm ?? null,
    comment: song.comment ?? null,
    sortName: song.sortName ?? null,
    musicBrainzId: song.musicBrainzId ?? null,
    displayArtist: song.displayArtist ?? null,
    displayAlbumArtist: song.displayAlbumArtist ?? null,
    displayComposer: song.displayComposer ?? null,
    explicitStatus: song.explicitStatus ?? null,
  };
}

export function toAlbumRow(
  album: AlbumWithSongsID3,
  coverArtPath: string | null,
): typeof albumsTable.$inferInsert {
  return {
    id: album.id,
    name: album.name,
    version: album.version ?? null,
    artist: album.artist ?? null,
    artistId: album.artistId ?? null,
    coverArt: album.coverArt ?? null,
    coverArtPath,
    songCount: album.songCount,
    duration: album.duration,
    playCount: album.playCount ?? null,
    created: album.created,
    starred: album.starred ?? null,
    year: album.year ?? null,
    genre: album.genre ?? null,
    played: album.played ?? null,
    userRating: album.userRating ?? null,
    musicBrainzId: album.musicBrainzId ?? null,
    displayArtist: album.displayArtist ?? null,
    sortName: album.sortName ?? null,
    originalReleaseDate: album.originalReleaseDate ?? null,
    releaseDate: album.releaseDate ?? null,
    isCompilation: album.isCompilation ?? null,
    explicitStatus: album.explicitStatus ?? null,
  };
}
